// ======================================================
// File Name : Reporting.jsx
// Purpose   : Page-level component for Reporting
// ======================================================

import { useEffect, useState } from 'react';
import { reportsApi } from '../../api/reports.api';
import { AppLayout } from '../../layout/AppLayout';
import { Pill } from '../../components/ui/ui';
import { Button } from '../../components/ui/Button';
import { Table } from '../../components/ui/Table';
import { EmptyState } from '../../components/common/EmptyState';
import { formatDate } from '../../utils/formatDate';

// ======================================================
// START: Page Component
// ======================================================

const ICO = {
    'depreciation-detail': 'ico-blue',
    'roll-forward': 'ico-teal',
    'form-4562': 'ico-purple',
    'disposal-gain-loss': 'ico-amber',
    reconciliation: 'ico-green',
    exceptions: 'ico-red'
};
const ICON = {
    'depreciation-detail': '▤',
    'roll-forward': '↻',
    'form-4562': '⊞',
    'disposal-gain-loss': '⊗',
    reconciliation: '✓',
    exceptions: '⚑'
};
const STATUS_TONE = { Ready: 'green', Draft: 'amber', Processing: 'blue' };
// ======================================================
// Function : Reporting
// Purpose  : React component that renders the 'Reporting' UI
// ======================================================

export function Reporting() {
    const [catalog, setCatalog] = useState([]);
    const [recent, setRecent] = useState([]);
    useEffect(() => {
        reportsApi.getCatalog().then(setCatalog);
        reportsApi.getRecent().then(setRecent);
    }, []);
    const columns = [
        { header: 'Report', render: (r) => r.name },
        { header: 'Book', render: (r) => r.book },
        { header: 'Period', render: (r) => r.period },
        { header: 'Generated By', render: (r) => r.generatedBy },
        { header: 'Date', render: (r) => formatDate(r.date) },
        { header: 'Format', render: (r) => r.format },
        { header: 'Status', render: (r) => <Pill tone={STATUS_TONE[r.status] ?? 'gray'}>{r.status}</Pill> }
    ];
    return (<AppLayout active="reporting" title="Reporting" crumb="Home / Reporting">
      <div className="page-header">
        <div>
          <h1>Reporting Center</h1>
          <p>Generate standard and custom fixed-asset reports for tax, book, and audit</p>
        </div>
        <Button variant="primary">+ Custom Report</Button>
      </div>

      <div className="grid grid-3 mb-4">
        {catalog.map((r) => (<div className="report-card" key={r.key}>
            <div className={`ri ${ICO[r.key] ?? 'ico-blue'}`}>{ICON[r.key] ?? '▤'}</div>
            <div>
              <h4>{r.name}</h4>
              <p>{r.description}</p>
            </div>
          </div>))}
      </div>

      <div className="card">
        <div className="card-head">
          <h3>Recently Generated Reports</h3>
          <select className="btn btn-ghost btn-sm">
            <option>All Books</option>
            <option>Federal Tax</option>
            <option>GAAP</option>
            <option>State No Bonus</option>
          </select>
        </div>
        {recent.length === 0 ? (<EmptyState title="No reports generated yet" description="Reports you generate will show up here."/>) : (<Table columns={columns} rows={recent} rowKey={(r) => `${r.name}-${r.date}`}/>)}
      </div>
    </AppLayout>);
}

// ======================================================
// END: Reporting
// ======================================================

// ======================================================
// END: Page Component
// ======================================================

