-- ======================================================
-- File Name : seed-asset-classes.sql
-- Purpose   : Default Asset Classes table (Configuration -> Asset Classes).
--             Values live ONLY here / in the DB - no copy in server code.
-- Safe to re-run: inserts only when asset_classes is empty.
-- ======================================================
CREATE TABLE IF NOT EXISTS asset_classes
(
    "sortOrder"     INTEGER PRIMARY KEY,
    name            TEXT NOT NULL,
    "propertyType"  TEXT NOT NULL,
    method          TEXT NOT NULL,
    "ratePct"       TEXT NOT NULL,
    convention      TEXT NOT NULL,
    life            TEXT NOT NULL,
    "bonusPct"      TEXT NOT NULL DEFAULT ''
);

INSERT INTO asset_classes ("sortOrder", name, "propertyType", method, "ratePct", convention, life, "bonusPct")
SELECT * FROM (VALUES
(0, '00.11', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(1, '00.11 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '10 years 0 months', ''),
(2, '00.11 - PRE TCJA', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(3, '00.11 - WBC', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(4, '00.12', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(5, '00.12 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(6, '00.12 - PRE TCJA', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(7, '00.12 - WBC', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(8, '00.13', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(9, '00.13 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '6 years 0 months', ''),
(10, '00.22', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(11, '00.22 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(12, '00.241', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(13, '00.241 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(14, '00.241 - WBC', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(15, '00.242', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(16, '00.242 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '6 years 0 months', ''),
(17, '00.242 - WBC', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(18, '00.25', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(19, '00.25 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(20, '00.27', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(21, '00.27 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '6 years 0 months', ''),
(22, '00.27 - WBC', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(23, '00.3', 'RP - Real Property', 'MC - MACRS', '150', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(24, '00.3 - ADS', 'RP - Real Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '20 years 0 months', ''),
(25, '00.3 - PRE TCJA', 'RP - Real Property', 'MC - MACRS', '150', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(26, '00.3 - WBC', 'RP - Real Property', 'MC - MACRS', '150', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(27, '1250', 'NR - Non-Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '39 years 0 months', ''),
(28, '1250 - ADS', 'NR - Non-Residential Real', 'AD - MACRS ADS', '100', 'MM - Mid-Month', '40 years 0 months', ''),
(29, '20.4', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(30, '20.5', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '3 years 0 months', ''),
(31, '27', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(32, '27.0 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '11 years 0 months', ''),
(33, '31.5', 'NR - Non-Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '31 years 6 months', ''),
(34, '36', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(35, '36.0 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '6 years 0 months', ''),
(36, '45', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(37, '45.0 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '12 years 0 months', ''),
(38, '45.0 - WBC', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(39, '48.37', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(40, '48.37 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '8 years 0 months', ''),
(41, '48.42', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(42, '48.42 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '10 years 0 months', ''),
(43, '57', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(44, '57.0 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '9 years 0 months', ''),
(45, '57.0 - PRE TCJA', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(46, '57.0 - WBC', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(47, '79', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(48, '79.0 - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '10 years 0 months', ''),
(49, 'Acquisition', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '0 years 0 months', ''),
(50, 'Alternative Energy Property', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(51, 'Alternative Energy Property - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '12 years 0 months', ''),
(52, 'Alternative Energy Property - WBC', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(53, 'Automobile', 'AL - Listed - Auto', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(54, 'Book Only', 'ND - Non-Depreciable Property', 'NO - No Depreciation', 'N/A', 'N/A', '0 years 0 months', ''),
(55, 'Book Only - ADS', 'ND - Non-Depreciable Property', 'NO - No Depreciation', 'N/A', 'N/A', '0 years 0 months', ''),
(56, 'Book Only - No Expense', 'ND - Non-Depreciable Property', 'NO - No Depreciation', 'N/A', 'N/A', '0 years 0 months', ''),
(57, 'Clean Fuel Luxury Vehicle', 'CF - Clean Fuel Luxury Vehicle', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(58, 'Commercial Property - 15-Year', 'LI - Leasehold Improvements - 15-Yr. Property', 'MS - MACRS Straight Line', '100', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(59, 'Commercial Property - NY Liberty Zone', 'CY - Commercial Property - NY LZ', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '39 years 0 months', ''),
(60, 'Conversion', 'ND - Non-Depreciable Property', 'NO - No Depreciation', 'N/A', 'N/A', '0 years 0 months', ''),
(61, 'Expense', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '0 years 1 month', ''),
(62, 'Furniture & Fixtures', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(63, 'Goodwill (including FASB142)', 'AM - Amortizable', 'SL - Straight Line', '100', 'FM - Full-Month', '15 years 0 months', ''),
(64, 'Indian Nonresidential Real', 'IN - Indian Nonresidential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '22 years 0 months', ''),
(65, 'Indian Personal', 'IP - Indian Reserv. - Personal', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '3 years 0 months', ''),
(66, 'Indian Real', 'IR - Indian Reserv. - Real', 'MC - MACRS', '150', 'AHY - Apply Mid-Quarter test (use HY)', '9 years 0 months', ''),
(67, 'INT-00.11', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '10 years 0 months', ''),
(68, 'INT-00.12', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(69, 'INT-RP39', 'NR - Non-Residential Real', 'AD - MACRS ADS', '100', 'MM - Mid-Month', '40 years 0 months', ''),
(70, 'INT-Software', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '3 years 0 months', ''),
(71, 'Intangible - SS', 'AM - Amortizable', 'SL - Straight Line', '100', 'FM - Full-Month', '10 years 0 months', ''),
(72, 'Intangibles', 'AM - Amortizable', 'SL - Straight Line', '100', 'FM - Full-Month', '0 years 0 months', ''),
(73, 'Intangibles - Other', 'AM - Amortizable', 'SL - Straight Line', '100', 'FM - Full-Month', '15 years 0 months', ''),
(74, 'Kuiper Manufacturing', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '10 years 0 months', ''),
(75, 'Kuiper Manufacturing - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '10 years 0 months', ''),
(76, 'Land', 'LR - Realty - Land', 'NO - No Depreciation', 'N/A', 'N/A', '0 years 0 months', ''),
(77, 'Land - ADS', 'LR - Realty - Land', 'NO - No Depreciation', 'N/A', 'N/A', '0 years 0 months', ''),
(78, 'Land - Tax Only', 'LR - Realty - Land', 'NO - No Depreciation', 'N/A', 'N/A', '0 years 0 months', ''),
(79, 'Land - Tax Only - ADS', 'LR - Realty - Land', 'NO - No Depreciation', 'N/A', 'N/A', '0 years 0 months', ''),
(80, 'Leasehold Improvements', 'NR - Non-Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '39 years 0 months', ''),
(81, 'Leasehold Improvements - NY Liberty Zone', 'LY - Leasehold Improvement - NY LZ', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '5 years 0 months', ''),
(82, 'Luxury Trucks & Vans', 'TL - Luxury Trucks & Vans', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(83, 'Office Equipment', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(84, 'On Tops', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '0 years 1 month', ''),
(85, 'OnTop - No Expense', 'PP - Personal Property', 'NC - No Calculation', '200', 'AHY - Apply Mid-Quarter test (use HY)', '0 years 0 months', ''),
(86, 'QIP', 'LI - Leasehold Improvements - 15-Yr. Property', 'MS - MACRS Straight Line', '100', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(87, 'QIP - 39', 'NR - Non-Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '39 years 0 months', ''),
(88, 'QIP - ADS', 'LI - Leasehold Improvements - 15-Yr. Property', 'SL - Straight Line', '100', 'AHY - Apply Mid-Quarter test (use HY)', '20 years 0 months', ''),
(89, 'QIP - PRE TCJA', 'NR - Non-Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '39 years 0 months', ''),
(90, 'QIP - WBC', 'LI - Leasehold Improvements - 15-Yr. Property', 'MS - MACRS Straight Line', '100', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(91, 'QLHI', 'LI - Leasehold Improvements - 15-Yr. Property', 'SL - Straight Line', '100', 'FM - Full-Month', '15 years 0 months', ''),
(92, 'Qualified Improvement Property - 15-yr Property', 'LI - Leasehold Improvements - 15-Yr. Property', 'MS - MACRS Straight Line', '100', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(93, 'Qualified Production Property', 'QP - Qualified Production Property', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '39 years 0 months', ''),
(94, 'Research & Development - Domestic', 'AM - Amortizable', 'SL - Straight Line', '100', 'HY - Half-Year', '5 years 0 months', ''),
(95, 'Research & Development - Foreign', 'AM - Amortizable', 'SL - Straight Line', '100', 'HY - Half-Year', '15 years 0 months', ''),
(96, 'Residential Rental Property - ADS Life 30', 'RR - Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '27 years 6 months', ''),
(97, 'Residential Rental Property - ADS Life 40', 'RR - Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '27 years 6 months', ''),
(98, 'Residential Rental Property - NY Liberty Zone', 'RY - Residential Rental Property - NY LZ', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '27 years 6 months', ''),
(99, 'Sec-59e', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '10 years 0 months', ''),
(100, 'Service Agreement', 'AM - Amortizable', 'SL - Straight Line', '100', 'FM - Full-Month', '10 years 0 months', ''),
(101, 'Software', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '3 years 0 months', ''),
(102, 'Software - ADS', 'PP - Personal Property', 'AD - MACRS ADS', '100', 'AHY - Apply Mid-Quarter test (use HY)', '3 years 0 months', ''),
(103, 'Software - WBC', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '3 years 0 months', ''),
(104, 'Sports Utility Vehicles', 'SV - Sport Utility Vehicles', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(105, 'Subsea Cable', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '25 years 0 months', ''),
(106, 'Subsea Cable - ADS', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '25 years 0 months', ''),
(107, 'Supplies', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '0 years 1 month', ''),
(108, 'Supplies - ADS', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '0 years 1 month', ''),
(109, 'Truck', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(110, 'U15YR No Bonus', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '15 years 0 months', '0'),
(111, 'Unspecified - Personal', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(112, 'Unspecified - Real', 'NR - Non-Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '39 years 0 months', ''),
(113, 'US-00.11', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', ''),
(114, 'US-00.11 No Bonus', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '7 years 0 months', '0'),
(115, 'US-00.12', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(116, 'US-00.12 No Bonus', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', '0'),
(117, 'US-00.241', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(118, 'US-00.241 No Bonus', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', '0'),
(119, 'US-00.3', 'RP - Real Property', 'MC - MACRS', '150', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(120, 'US-00.3 No Bonus', 'RP - Real Property', 'MC - MACRS', '150', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', '0'),
(121, 'US-23.0', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(122, 'US-24.1', 'PP - Personal Property', 'MC - MACRS', '200', 'AHY - Apply Mid-Quarter test (use HY)', '5 years 0 months', ''),
(123, 'US-Intangibles-15', 'AM - Amortizable', 'SL - Straight Line', '100', 'FM - Full-Month', '15 years 0 months', ''),
(124, 'US-QLHI', 'LI - Leasehold Improvements - 15-Yr. Property', 'MS - MACRS Straight Line', '100', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', ''),
(125, 'US-QLHI No Bonus', 'NR - Non-Residential Real', 'MS - MACRS Straight Line', '100', 'AHY - Apply Mid-Quarter test (use HY)', '15 years 0 months', '0'),
(126, 'US-RP31.5', 'NR - Non-Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '31 years 6 months', ''),
(127, 'US-RP39', 'NR - Non-Residential Real', 'MS - MACRS Straight Line', '100', 'MM - Mid-Month', '39 years 0 months', ''),
(128, 'US-Software', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '3 years 0 months', ''),
(129, 'US-Software No Bonus', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '3 years 0 months', '0'),
(130, 'Utility Owned Substation', 'PP - Personal Property', 'SL - Straight Line', '100', 'FM - Full-Month', '10 years 0 months', '')
) AS v("sortOrder", name, "propertyType", method, "ratePct", convention, life, "bonusPct")
WHERE NOT EXISTS (SELECT 1 FROM asset_classes);
